package com.file.db;

import com.sun.org.apache.xalan.internal.xsltc.compiler.util.Util;

import java.sql.*;

/**
 *
 */
public class DerbyTest {



    public static void main(String[] args) throws ClassNotFoundException, SQLException {
        //加载嵌入式derby的JDBC驱动类
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
        //连接指定的derby数据库
        Connection conn = DriverManager.getConnection("jdbc:derby:D:/derby-demo;create=true","","");

        System.out.println(conn);

        Statement sm=conn.createStatement();
        //sm.execute("insert into file(uuid,size,type,name,old_name,create_time,path) values('asd',1000,'10','name','oldname','2019-10-10 08:08:08','path') ");

        ResultSet rs=sm.executeQuery("SELECT * FROM file WHERE uuid= '04c8b37f-6d74-4903-9e8b-9a93e8f3e8af'");
        while(rs.next()){
            System.out.println(rs.getString("uuid"));
        }

        /*ResultSet rs=sm.executeQuery("SELECT * FROM file");
        while (rs.next()){
            System.out.println(rs.getInt(1));
            System.out.println(rs.getString(2));
            System.out.println(rs.getString(3));
            System.out.println(rs.getString(4));
            System.out.println(rs.getString(5));
            System.out.println(rs.getTimestamp(7));
        }*/




        /*while (rs.next()){
            System.out.println(rs.getInt(1));
            System.out.println(rs.getString(2));
            System.out.println(rs.getString("age"));
        }*/

        /*sm.execute("create table file(\n" +
                "   ID  INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),\n" +
                "   uuid VARCHAR(100),\n" +
                "   size INTEGER,\n" +
                "   type VARCHAR(20),\n" +
                "   name VARCHAR(100),\n" +
                "   old_name VARCHAR(100),\n" +
                "   create_time TIMESTAMP,\n" +
                "   path VARCHAR(100),\n" +
                "   constraint PK_FILE primary key (ID)\n" +
                ")");*/
    }


}
